language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/ESP8266/ESP8266.ino

install:
    - pip install -U platformio
    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/64/ArduinoJson
    # http://platformio.org/lib/show/89/PubSubClient

    - platformio lib -g install 64 89

script:
    - platformio ci --lib="." --board=nodemcuv2
